### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [openSUSE/permissions#3]
Would you like to add more error handling for return values from functions like the following?
- [fclose](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fclose.html) ⇒ [check_fscaps_enabled](https://github.com/openSUSE/permissions/blob/fbf4adb54e901022624acc013793314366f54222/chkstat.c#L540)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [main](https://github.com/openSUSE/permissions/blob/fbf4adb54e901022624acc013793314366f54222/chkstat.c#L948)

**Comment by maltek** [comment]
I don't see any sensible error handling that could be added in these two locations.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
