### ISSUE TITLE
Packaging this to other distributions?

### ISSUE THREAD

**Issue by q2dg** [openSUSE/permissions#4]
I like this tool but being only available in Suse it's a big problem to embrace it. Could it be possible to package in a .deb form to Debian/Ubuntu-like distros and maybe in a .rpm form to Fedora/CentOS ones?
Thanks a lot

**Comment by msmeissn** [comment]
this kind of needs the support by other packages (works with %post snippets in the rpms). But the package itself can be offered, sure.

**Comment by mgerstner** [comment]
Closing this since this is nothing we as SUSE can spend ressources on. We'd need volunteers to do that. We could only help in improving compatibility with other distros.
